# You have a list of temperatures recorded in Celsius. Your task is to:
##### Create a NumPy array from the given list.
##### Convert all temperatures from Celsius to Fahrenheit. The formula is F = C* 1.8 + 32.
##### Print the new Fahrenheit array.

In [20]:
import numpy as np

In [21]:
inputDataCelsius = np.array(input("Enter last five days temperatures in celsius: ").split(), dtype = np.float64)
dataFahrenheit = (inputDataCelsius * 1.8) +32
dataFahrenheit

array([78.8, 82.4, 86. , 87.8])

You have a Python list containing the lap times (in seconds) for an athlete.

Task:

Convert the list into a NumPy array.
Print the array's shape, size, and data type.
The athlete wants to see their times in minutes. Create a new array by dividing all the lap times by 60.
Print the new array of lap times in minutes.


In [22]:
lst = [67, 88, 121, 114, 78]
ndarray = np.array(lst, dtype=np.int32)
print(ndarray.shape)
print(ndarray.size)
print(ndarray.ndim)
print(ndarray.dtype)
print(type(ndarray))
ndarray

(5,)
5
1
int32
<class 'numpy.ndarray'>


array([ 67,  88, 121, 114,  78], dtype=int32)

In [23]:
inMinute = ndarray/60
inMinute = inMinute.astype(np.float16)
inMinute

array([1.116, 1.467, 2.018, 1.9  , 1.3  ], dtype=float16)